easy_admin:
    entities:
        # List the entity class name you want to manage
        User:
            label: 'Utilisateur'
            list:
                title: 'Utilisateur'
                fields:
                    - id
                    - surname
                    - email
                    - { property: 'image', type: 'image', base_path: '%app.path.upload%' }
            show:
                fields:
                    - { property: 'image', type: 'image', base_path: '%app.path.upload%' }
            form:
                fields:
                    - surname
                    - email
                    - password
                    - { property: 'imageFile', type: 'vich_file' }
            class: App\Entity\User
        Movie:
            label: 'Film'
            list:
                title: 'Film'
                fields:
                    - id
                    - title
                    - pitch
                    - realisator
                    - date
                    - { property: 'image', type: 'image', base_path: '%app.path.upload%' }
            show:
                fields:
                    - { property: 'image', type: 'image', base_path: '%app.path.upload%' }
            form:
                fields:
                    - title
                    - pitch
                    - date
                    - realisator
                    - { property: 'imageFile', type: 'vich_file' }
            class: App\Entity\Movie
        Article:
            label: 'Article'
            list:
                title: 'Article'
                fields:
                    - id
                    - title
                    - sub_title
                    - resume
                    - content
                    - author
                    - category
                    - date
                    - { property: 'image', type: 'image', base_path: '%app.path.upload%' }
            show:
                fields:
                    - { property: 'image', type: 'image', base_path: '%app.path.upload%' }
            form:
                fields:
                    - title
                    - sub_title
                    - resume
                    - content
                    - author
                    - category
                    - date
                    - { property: 'imageFile', type: 'vich_file' }
            class: App\Entity\Article
        Bds:
            label: 'Bds'
            list:
                title: 'Bds'
                fields:
                    - id
                    - title
                    - pitch
                    - author
                    - date
                    - { property: 'image', type: 'image', base_path: '%app.path.upload%' }
            show:
                fields:
                    - { property: 'image', type: 'image', base_path: '%app.path.upload%' }
            form:
                fields:
                    - title
                    - pitch
                    - date
                    - author
                    - { property: 'imageFile', type: 'vich_file' }
            class: App\Entity\Bds
        Comment:
            class: App\Entity\Comment
        Category:
            class: App\Entity\Category
        PostLike:
            class: App\Entity\PostLike
        Quote:
            class: App\Entity\Quote
        Links:
            class: App\Entity\Links
        Stars:
            class: App\Entity\Star


